django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html, setup.py
When using the django_rq.urls, a depreciation warning is thrown because job.status is depreciated in python-rq. This prevents you from viewing the jobs entirely. The templates have been updated accordingly.
Closes #88.
=> fix(django-rq/templates): updated job.status to job.get_status

django_rq/queues.py
The addition of a `strict_redis` kwarg on `get_connection()` allows projects that want (or need) to take advantage of `redis.StrictRedis()` to do so in a more pythonic way: without having to manually set up said connections.
=> Allow connection to use StrictRedis instead of Redis

README.rst
This command exists since 0.6, but was not documented in the README.
=> Add rqscheduler command to RQ Scheduler section of README

.travis.yml, django_rq/queues.py, django_rq/tests/tests.py
Hi,
There's still warning on test with django 1.8
```
RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
RemovedInDjango19Warning)
```
As for the test ``test_empty_queue_setting_raises_exception``, I deleted it since I can't figure out how to fix it.
Before django 1.7, the `django_rq.settings` file is loaded AFTER the test function is called.
However in 1.7 and 1.8, the `django_rq.settings` file is loaded BEFORE the test function, hence the QUEUES variable will always have a value and results in no exception.
=> Update django-rq compatibility with django 1.7/1.8

django_rq/queues.py
This should resolve issue #101. I ran the tests locally and they pass. Please note that when you run the tests you get a new warning.
```
RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
```
I'm not sure how or if this needs to be resolved.
=> Fixed the RemovedInDjango19Warning deprecation warning

django_rq/settings.py
This change makes the ordering of queues deterministic across multiple instances of `django-rq`. This means that in load-balanced environments (like Heroku), a path like `/rq/queues/1` will point to the same queue regardless of the instance that serves the request.
=> Sort the queues by name

README.rst
This raises a cryptic exception:
Traceback (most recent call last):
File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
fn(*args, **kwargs)
File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
autoreload.raise_last_exception()
File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
six.reraise(*_exception)
File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
fn(*args, **kwargs)
File "/vagrant/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File …
=> Typo in urls.py code example in README

.travis.yml, README.rst, django_rq/templates/django_rq/clear_queue.html, django_rq/templates/django_rq/confirm_action.html, django_rq/templates/django_rq/delete_job.html, django_rq/templates/django_rq/index.html, django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html, django_rq/templates/django_rq/stats.html, django_rq/test_settings.py, setup.py
From the docs of the django project:
One deprecated feature worth noting is the shift to “new-style” url tag. Prior to Django 1.3, syntax like {% url myview %} was interpreted incorrectly (Django considered "myview" to be a literal name of a view, not a template variable named myview). Django 1.3 and above introduced the {% load url from future %} syntax to bring in the corrected behavior where myview was seen as a variable.
The upshot of this is that if you are not using {% load url from future %} in your templates, you’ll need to change tags like {% url myview %} to {% url "myview" %}. If you were using {% load url from future %} you can simply remove that line under Django 1.5
This tag shouldn't be necessary anymore since Django 1.5.
=> Removed 'load url from future' for compatibility with Django 1.9

django_rq/tests/urls.py, django_rq/urls.py
This syntax is compatible with all past and, as far as the current
deprecation timeline is concerned, future versions of Django.
=> Use future-proof URLconf format.

README.rst, django_rq/queues.py, django_rq/test_settings.py, django_rq/tests/tests.py
when doing config via env vars it's nice to be able to pass the whole configuration in one url string
underlying redis-py library supports this
=> allow to specify db number in url

django_rq/settings.py
It sorts RQ_QUEUES only by key (queue name). 
This issue was already resolved in #118  but unfortunately it doesn't work in our environment (behind load-balancer). 
`.../django-rq/queues/3/` each request point to the different queue.
=> sort the queues only by name

README.rst, django_rq/management/commands/rqscheduler.py, django_rq/settings.py, django_rq/workers.py
I found there were a couple problems with the implementation for EXCEPTION_HANDLERS and cleaned them up.
1. The README documentation didn't match how it was implemented.
2. The implementation bypassed the django_rq settings and accessed an `RQ` settings variable directly.
=> Clean up EXCEPTION_HANDLER implementation

README.rst, django_rq/decorators.py, django_rq/management/commands/rqworker.py, django_rq/queues.py, django_rq/test_settings.py, django_rq/tests/tests.py
I don't know why It is not implemented yet, but I think it is useful. For example: We have the project,  and we don't want to  run redis at the test environment or in other special environment. Yeah, writing something like this: 
```python
if getattr(settings, 'DIRECT_CALL', False):
job()
else:
job.delay()
```
at every call is not good idea (for me)
Next changes give for us more clear way to do this, I can use custom Queue class for this:
```python
class DummyQueue(DjangoRQ):
def enqueue_call(self, func, args=None, kwargs=None, timeout=None,
result_ttl=None, ttl=None, description=None,
depends_on=None, job_id=None, at_front=False):
return partial(func, args=args, kwargs=kwargs)
``` 
and then use them at the settings.
I think somebody will find other cases to use this ability: adding extra …
=> Custom queue class.

django_rq/templates/django_rq/job_detail.html
Hi,
I created this pull request, because I want to be able to see job return value on job django admin detail page.
It works for job in any state. (It display None if no result yet)
=> show job result on job django admin detail page.

django_rq/templates/django_rq/jobs.html, django_rq/templates/django_rq/requeue_all.html, django_rq/urls.py, django_rq/views.py
I'm using django-rq to push through lots of jobs everyday (20k+) and sometimes a bunch of them will fail at once due to unforeseen issues (> 1000 failed jobs).   It is a bit cumbersome right now to requeue everything in 100 job batches using the only admin actions.  Thus, I've added in a "Requeue All" feature / button that only shows up on failed queue, similar to how Empty Queue works across all the queues.  Makes it much easier / faster to requeue a bunch of failed tasks after a problem is resolved.
Just let me know if you have any questions or need additional updates to approve pull request - happy to help.  Django-rq has worked great for our needs!
=> Adding in Requeue All feature for Failed Queues

django_rq/management/commands/rqworker.py
The use case is the following : 
- you run `rqworker` supervised by [supervisord](https://supervisord.org)
- you run any system operation on redis, like updating its configuration
- you restart redis
- the worker detects Redis is down and quits with the message 
> Registering death
but also with exit code 0 which is not in Supervisor"s unexpected exit codes.
Therefore supervisord will simply not restart the `rqworker` under supervision as it thinks it has stopped normally.
Exiting with exit code 1 in case of connection error fixes this.
=> Added exit code 1 in case of connection error

django_rq/management/commands/rqworker.py, django_rq/tests/tests.py
While converting commands to argparse, the `--burst` flag to the `rqworker` command was badly transformed to a flag needed a parameter.
=> Fixed --burst boolean arg of rqworker command

django_rq/management/commands/rqworker.py, django_rq/test_settings.py, django_rq/tests/tests.py
This fixes a regression introduced by 2eb4afad which broke passing of queues on Django 1.9 (as reported in #181).
=> fix argument parsing to work on Django 1.8, 1.9, and 1.10

django_rq/queues.py, django_rq/tests/tests.py
=> consider one and only one failed queue for each distinct redis connection

README.rst
deprecated since 1.8, removed in 1.10
=> patterns function removed from django

django_rq/tests/tests.py, django_rq/views.py, django_rq/workers.py
In the view `stats`, the query `Worker.all()` is applied to every queue
in the settings, even those which have the same configuration and, thus,
would give the same response.
This commit aims to avoid all unnecessary queries by calling a
preprocessor.
=> Fix #231 Improves interface response

.gitignore, integration_test/_tests.py, integration_test/requirements.txt
Also 
- gitignore pycharm config
- Use Django's six (fixes issue that six was missing from test requirements)
- Pycharm optimise imports on `integration_test/_tests.py`
=> Bump test requirements

.gitignore, django_rq/views.py
Only load job ids when doing requeue all, instead of instantiating job objects, to save resources.
Also added gitignore of pycharm project.
=> Optimise requeue all - resolves #244

README.rst, django_rq/management/commands/rqworker.py, setup.py
Hello,
Added same support rqworker original command has for sentry.
Use ``sentry-dsn`` parameter when running rqworker. ``./manage.py rqworker sentry-dsn=https://*****@sentry.io/222222``
=> Add support for sentry parameter

django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html, django_rq/templatetags/django_rq.py
A simple fix to allow object passed into to_localtime to be None and not cause an exception to be thrown. Specifically fixes an issue that I was seeing when viewing the deferred queue.
Closes #250
=> Fix issue displaying deferred queue

django_rq/templates/django_rq/stats.html, django_rq/templates/django_rq/worker_details.html, django_rq/utils.py
rq 0.9.x introduce some new worker statistics. This PR shows that in the django admin worker details page.
Also, added `oldest_queued_timestamp` to queue statistics
=> Show New statistics from rq 0.9.x on worker details page

.travis.yml, Makefile, README.rst
The PyPI page for django-rq looks really ugly, it is rendering its content as plain text, instead of accepting the RST formatting: https://pypi.python.org/pypi/django-rq
This pull request fixes the RST errors in the README.rst file. It also adds a test to make sure this gets checked before being published to PyPI.
=> Fix RST formatting errors in README.rst

README.rst, django_rq/decorators.py, django_rq/jobs.py, django_rq/management/commands/rqworker.py, django_rq/queues.py, django_rq/settings.py, django_rq/tests/tests.py, django_rq/workers.py
What has been changed:
- Added `RQ.WORKER_CLASS` setting to complement `RQ.QUEUE_CLASS`;
- Changed rqworker management command to use defaults via `get_worker_class`/`get_queue_class` instead of defining it's own;
- in queues.py `get_queue` and `get_queue_by_index` now have `**kwargs` to allow passing any additional kwargs to queue class constructor;
- in worker.py add `get_worker_class` and use it in other functions;
- isort in all changed files.
=> More consistent usage of queue class / worker class overriding

README.rst, django_rq/management/commands/rqworker.py
I really needed this feature since I'm deploying with dokku and I don't want to store DSN in ini files.
I use environment variables and load them into settings instead. So getting DSN from settings is essential to me.
This is how it's done in https://github.com/rq/rq/blob/master/rq/cli/cli.py#L192
=> Ability to load SENTRY_DSN for rqworker from Django settings

django_rq/templates/django_rq/index.html
Noticed a minor styling issue in the Django RQ admin section. The table appears to be set to a fixed width of 498px, this commit aims to resolve the issue by setting the width to 100%.
**Bug:** _Width set to 498px._
**Fix:** _Width set to 100%._
=> Removed fixed table width.

README.rst
Change README.rst to use path() instead of url() in the urls.py section to make it more Django 2.0
=> In README.rst change the use of url() for Django >= 2.0 to path().

README.rst, django_rq/queues.py, django_rq/test_settings.py, django_rq/tests/tests.py, django_rq/utils.py, setup.py
The idea here is to be able to specify in settings a list of sentinels from which the connection to master will be obtained. It seems to be working fine for me, but I may have missed something. Can you please have a look @selwin ?
=> Added support for using redis sentinels.

.travis.yml, README.rst, django_rq/queues.py, django_rq/tests/tests.py, setup.py
Note that the new version of the dependency rq also did the same rename
for the same reason.
The variable `_async` was also renamed to `_is_async`.
Test in Python 3.7 and mark 3.7 as supported.
Fixes #295
=> Rename `async` to `is_async` to support Python 3.7

README.rst, django_rq/queues.py, django_rq/tests/settings.py, django_rq/tests/tests.py
* fixes #302 
* added support to pass additional connection kwargs to Sentinel
=> Fix how django-rq connects to Sentinel's

README.rst, django_rq/queues.py
this will allow you to provide your own redis connection object instead of creating one internally. 
This is done because every time we create a queue, it ends up creating a new connection object which in turn causes too many connections in redis.
=> provide connection as keyword argument for get_queue method

README.rst, django_rq/management/commands/rqworker.py
allow disabling sentry integration in the case where the project use sentry-sdk as `SENTRY_DSN` is not compatible between `sentry_sdk` and `raven` (missing secret key, a.k.a. password)
=> add argument to disable sentry integration

.travis.yml, django_rq/queues.py, django_rq/tests/fixtures.py, django_rq/tests/settings.py, django_rq/tests/tests.py
As per subject, solves #292.
Thanks for the awesome work!
=> Scheduler now respects default timeout and result_ttl

django_rq/management/commands/rqworker.py, django_rq/tests/tests.py
In our local environment we use the config var "SENTRY_SDK" for our actual sentry_sdk package variable in settings.
With that variable set I was unable to set --sentry-sdk="" with the environment variable still set because the line deleted would override the option passed in and thus rqworker would crash until we changed our config variable to something other than SENTRY_SDK.
=> Remove redundant sentry_dsn config line

django_rq/management/commands/rqworker.py
I discovered that verbosity parameter is not honored because [worker gets called with default info parameter](https://github.com/rq/rq/blob/master/rq/worker.py#L443).
=> Honor logging level set by --verbosity

django_rq/templates/django_rq/jobs.html, django_rq/templates/django_rq/stats.html, django_rq/tests/test_views.py, django_rq/urls.py, django_rq/utils.py, django_rq/views.py
Starting with 1.2.0 rq  supports job scheduling without additional requirements, so it would be nice to support stats for scheduled jobs.
This line https://github.com/rq/django-rq/pull/400/files#diff-51cc121b676f5b91f7ee8499cc586a1dR173 may not be the best idea, but I don't see a clearer way of adding this attribute without additional changes in rq.
=> Stats for scheduled jobs

django_rq/views.py
Django's [AdminSite.each_context()](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.AdminSite.each_context) method adds context like the site_header that's used by the admin templates to render the view. It's currently missing from all of the `context_data` dicts provided to the render function. This is why the view still says "Django Administration" even if you've adjusted your site's name. 
This is also problematic as some 3rd party skins / themes for Django expect to be able to render their templates with information from the request.context, which is missing. I ran into this with the `available_apps` list in Django Suit.
=> Added AdminSite.each_context() to context_data dicts in views

django_rq/management/commands/rqworker.py
I added support for ` --with-scheduler` based on https://github.com/rq/rq/blob/master/docs/docs/scheduling.md#running-the-scheduler
=> Allow worker to run with scheduler enabled

django_rq/tests/test_views.py
There is a small typo in django_rq/tests/test_views.py.
Should read `requeuing` rather than `requeueing`.
=> docs: Fix simple typo, requeueing -> requeuing

django_rq/decorators.py, django_rq/queues.py, django_rq/tests/tests.py
This library has a very useful setting to set a default `result_tt`, but it is not always respected.
Two issues with the `DEFAULT_RESULT_TTL` setting should be fixed with this PR:
1. `DEFAULT_RESULT_TTL` is ignored in the `job` decorator when it is set to zero.
2. `DEFAULT_RESULT_TTL` is completely ignored in the `enqueue` method.
=> Fix ignored DEFAULT_RESULT_TTL

README.rst
When specifying arguments to the underlying RQ job decorator, the
queue name must be given explicitly which may not be obvious because
of the simple @job usage.
=> README: add @job arguments usage

.gitignore, Pipfile, README.rst, django_rq/management/commands/rqworker.py, django_rq/tests/tests.py
This is a simpler alternative to #441. Fixes #440 and #427. 
---
This PR changes how the `rqworker` command integrates with Sentry.
At the current time, if you pass in `sentry-dsn`, **or** have `django.conf.settings.SENTRY_DSN` set, then the command will reinitialise Sentry using a limited subset of options, overriding any existing Django setup. The options supported are `debug` and `ca_certs`, and the list of integrations is restricted to `RqIntegration`. 
This PR prevents the possible clash with Django settings by removing the fallback to `SENTRY_DSN`. If you pass `sentry-dsn` to the command, it will use it, and ignore any existing Django settings configuration. If you don't pass it, it will do nothing - i.e. it will rely on any existing Django configuration.
In addition, this does away …
=> Update rqworker command Sentry configuration (alternative version)

django_rq/queues.py
Hi, I'm a bit new to contributing to a project, happy to make changes as suggested.
Context: This was prompted by not being able to connect to Redis on Heroku.
https://help.heroku.com/HC0F8CUS/redis-connection-issues
I needed to be able to set the ssl_cert_reqs.
Also, question: Should we add all the params below instead of a select few?
https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/client.py#L737-L749
Thanks!
=> Allow setting ssl_cert_reqs and username in get_redis_connection

README.rst
A small change here, `get` is not a `django_rq` attribute, it should be `get_queue`.
=> Fix module django_rq has no attribute get

README.rst
dictionary.itervalues() was removed in python 3. Updated sync mode test example to use dictionary.values() instead.
=> sync mode test example to support python 3

django_rq/queues.py
Adds the ability to create a dict within the queue definition called `REDIS_CLIENT_KWARGS` of which all kwargs will be passed to the Redis client.
This allows control of timeouts, health check intervals etc. directly with the client.
I broke the line with a small restyle as it was getting very long.
=> Add ability to pass arbitrary Redis client kwargs

django_rq/templates/django_rq/job_detail.html, django_rq/templatetags/django_rq.py, django_rq/tests/tests.py
Hi, this PR tries to solve issue #479 .
A new template tag `force_escape` is created and used in `job_detail.html` to escape `args` and `kwargs` of a job function event if they are `SafeString`
=> Create force_escape template tag to escape text marked as safe

README.rst
At the bottom of the README was a link to: https://github.com/coremke/django-suit-rq
this project was not updated since 2016.
I guess it makes sense to remove this link from the README
=> removed link to django-suit-rq

django_rq/queues.py
Based on https://github.com/rq/django-rq/issues/508 fixed the issue
when redis URL given is non-ssl
Just created base PR here with the idea of https://github.com/rq/django-rq/issues/508#issuecomment-971765269.
Should fully fix https://github.com/rq/django-rq/issues/508
=> [fix] Fixed use of ssl_cert_reqs for non ssl

django_rq/views.py
When using admin view to manually enqueue a scheduled job, it is not removed from the ScheduledJobRegistry (I think this was missed when implementing the scheduler).
=> Remove job from ScheduledJobRegistry if enqueued manually

README.rst
Completing Readme - added information about RQ build-in scheduler and highlight that stats display only build-in scheduler jobs.  See #506
=> Mentioned RQ built-in scheduler in Readme

django_rq/management/commands/rqenqueue.py, django_rq/management/commands/rqscheduler.py, django_rq/management/commands/rqworker.py, django_rq/templatetags/jquery_path.py
The minimum supported version of Django is now 2.0. All these
checks for 1.9 and 1.10 are no longer needed.
=> Remove usage of deprecated LooseVersion

django_rq/management/commands/rqworker.py
Allow `rqworker` management command to accept `max-jobs` option which RQ provide to limit the number of jobs to execute.
=> Add max-jobs option in command

README.rst, django_rq/tests/test_views.py, django_rq/thread_queue.py, integration_test/README.md
There are small typos in:
- README.rst
- django_rq/tests/test_views.py
- django_rq/thread_queue.py
- integration_test/README.md
Fixes:
- Should read `response` rather than `responsce`.
- Should read `overridden` rather than `overriden`.
- Should read `interaction` rather than `interraction`.
- Should read `deferred` rather than `deffered`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

README.rst, django_rq/queues.py, django_rq/tests/settings.py, django_rq/tests/tests.py
resolves #575
- Passing username to Sentinel args
- Updated connection_kwargs and sentinel_kwargs according to [redis-py doc](https://redis.readthedocs.io/en/stable/connections.html#sentinel-client)
- Udpated the documentation
- Updated the tests
=> Feat: Add username support for Sentinel

django_rq/management/commands/rqworker.py, django_rq/tests/tests.py
@selwin adding support for custom serializers (trying to keep up with rq worker arguments that are not available for the rqworker command). Tests included.
=> Add support for rqworker's custom Serializer

django_rq/tests/test_views.py, django_rq/urls.py
Virtually any string is a valid rq job_id. I think the only real requirement is that it be a valid redis key, and Redis supports arbitrary binary keys. This PR expands the url patterns so that fewer customized job_ids cause a 500 while viewing the queue.
=> More permissive urls for customized job_ids

django_rq/management/commands/rqstats.py
Regarding #416
Add `Failed` column to `rqstats` management command. It would look like this
```
Django RQ CLI Dashboard
------------------------------------------------------------------------------------------
| Name           |    Queued |    Active |  Deferred |  Finished |    Failed |   Workers |
------------------------------------------------------------------------------------------
| default        |         0 |         0 |         0 |         2 |         0 |         0 |
------------------------------------------------------------------------------------------
```
=> Add failed jobs column to rqstats command

django_rq/templates/django_rq/job_detail.html
This PR fixes a minor layout shift issue in the job detail page of the admin panel. 
Before : 
After :
=> Fix layout of the deletelink button

django_rq/templates/django_rq/job_detail.html, django_rq/templatetags/django_rq.py
Fix #606 
By using a custom template tag, we can ensure that the function `items` is called instead of the key inside the dictionary
=> Add template tag items to always call dictionary function

django_rq/queues.py, django_rq/tests/settings.py, django_rq/tests/tests.py, django_rq/utils.py, django_rq/views.py
Related to this issue: https://github.com/rq/django-rq/issues/626 
We want to be able to add the serializer when creating the Django RQ queue. This serializer should then automatically be used when fetching the jobs so that we do not get `DeserializationError` in the Django RQ dashboard.
=> Specify queue serializer when creating Django RQ queue

django_rq/templatetags/django_rq.py
From the release notes: https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0
> The django.utils.timezone.utc alias to datetime.timezone.utc is removed.
Resolves #610
=> Use datetime.timezone.utc as Django 5.0 removed the alias.

django_rq/utils.py
When the `db` value is not included explicitly in the connection kwargs the default `0` db is used but this is not reflected in the connection kwargs.
Closes gh-632
=> Account for missing db in connection kwargs

.github/workflows/test.yml, django_rq/management/commands/rqpool.py, django_rq/management/commands/rqworker-pool.py, django_rq/management/commands/rqworker.py, django_rq/tests/tests.py, django_rq/utils.py
Ref #621 
---------
1. Generate `x` number of jobs
2. Run rqworker and rqpool commands in burst mode with verbosity level of 0
3. Memory usage and time are measured using the following utility function: https://gist.github.com/chromium7/802741a5767cec234aef94e7b6149c92
|  | rqworker | rqpool | rqpool | rqpool |
|--------|--------|--------|--------|--------|
| Number of Worker | 4 | 4 | 8 | 24 |
| Number of Jobs | 1000 | 1000 | 1000 | 1000 |
| Time Elapsed | 10.336005s (per worker) | 11.275090s | 7.396444s |  7.317025s | 
| Peak Memory Usage |  0.51407MB (per worker) | 0.204661MB | 0.214324MB | 0.252267MB | 
```
$ python manage.py rqworker --burst --verbosity 0 & python manage.py rqworker --burst --verbosity 0 & python manage.py rqworker --burst --verbosity 0 & python manage.py rqworker …
```
=> Add RQPool management command

django_rq/utils.py
If a port is not specified explicitly `Redis` uses its default port instead, and it may not always appear in the connection kwargs.
Related to https://github.com/rq/django-rq/pull/633
=> fix: use default redis port when not specified in connection kwargs

CHANGELOG.md, README.rst, django_rq/__init__.py, setup.py
The tag `v2.10.1` looks like it contains commits that are not in the repository.
=> merge commits 2.10.1 into master

django_rq/apps.py
```
django_rq.Queue: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
````
=> Fixed models.W042 warning.

django_rq/queues.py, django_rq/workers.py
Except for `django_rq.job`, which is too complicated to type properly.
=> Add type annotations to most public functions

README.rst, django_rq/management/commands/rqresume.py, django_rq/management/commands/rqsuspend.py, django_rq/tests/tests.py
Add wrapper management commands for suspend and resume. See docs for details.
Closes https://github.com/rq/django-rq/issues/206
=> Add suspend command

django_rq/workers.py
This communicates more information to IDEs and type checkers, making the function easier to use.
Having regular parameters after `*args` has been possible since Python 3.0.
=> get_worker: replace special kwargs with separate parameters

.github/workflows/test.yml, django_rq/management/commands/rqstats.py
Currently, when PyYAML is not installed, `rqstats -y` prints an error message, but it still exits with a 0 exit code, indicating success. Fix that, along with a few related issues:
* The error message was printed to stdout rather than stderr.
* The name of the library in the message was incorrect (LibYAML is a C library; the Python library is PyYAML).
After this change, you need to install PyYAML to run the testsuite, so modify the GitHub workflow accordingly. Also, make sure to install all packages at once, to make sure that later install commands don't overwrite the result of the earlier ones.
=> Make `rqstats -y` fail when PyYAML is not installed

django_rq/utils.py
When using Sentinels connection to Redis instead of a "single host", when displaying the `views.stats` view, the following exception is raised:
```py
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
response = view_func(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Handle the case where the connection to redis instances use Sentinels in `get_scheduler_statistics()`

.github/workflows/test.yml, django_rq/admin.py, django_rq/decorators.py, django_rq/management/commands/rqenqueue.py, django_rq/management/commands/rqscheduler.py, django_rq/management/commands/rqstats.py, django_rq/management/commands/rqworker-pool.py, django_rq/management/commands/rqworker.py, django_rq/queues.py, django_rq/settings.py, django_rq/tests/fixtures.py, django_rq/tests/settings.py, django_rq/tests/test_views.py, django_rq/tests/tests.py, django_rq/tests/urls.py, django_rq/utils.py, django_rq/views.py, setup.cfg, setup.py
I was going to contribute my typing for the `@job` decorator that was missing from https://github.com/rq/django-rq/pull/656, but I then realized there was no way to check if the annotations were correct, so I added `mypy` to the testing matrix
=> test type annotations with mypy

django_rq/decorators.py
This change adds typing to the `@job` decorator which was missing from https://github.com/rq/django-rq/pull/656.
=> Type `@job` decorator

django_rq/management/commands/rqworker.py
Django-rq currently does not expose the --max-idle-time flag that python-rq is able to use under the hood to gracefully shut down a worker after a given amount of seconds. Exposing this functionality proves useful in the event when django-rq workers are run within an autoscaling situation where scale-down time cannot be controlled (e.g.: Azure Container Apps).
By running the worker with `./manage.py rqworker --max-idle-time 60 default` the worker can gracefully shutdown before it gets killed by autoscaling, avoiding interrupted jobs that fail with an error of:
`Work-horse terminated unexpectedly; waitpid returned 15 (signal 15);`
Since `--max-jobs` is already exposed in the rqworker management command, exposing this option is trivial.
Testing process:
- When the flag is not used, the …
=> Expose --max-idle-time RQ flag in rqworker management command

django_rq/utils.py, django_rq/views.py
This change uses the new ``registry.get_job_and_execution_ids`` instead of the updated ``registry.get_job_id`` which no longer returns the execution id.
fixes: #697
=> fix ``registry.get_job_id`` not returning execution id anymore

setup.py
This change fixes a typo in setup.py package_data which prevents the type information from being exported.
fixes: https://github.com/rq/django-rq/issues/699
=> fix typo in setup.py package_data

django_rq/templates/django_rq/job_detail.html
This change removes the object-tools from the job detail-view.
fixes: https://github.com/rq/django-rq/issues/698
x-ref: https://code.djangoproject.com/ticket/36331
x-ref: https://github.com/django/django/pull/19389
=> fix Django admin object-tools breaking job detail view

django_rq/tests/utils.py, django_rq/utils.py
x-ref: https://github.com/redis/redis-py/pull/3614
x-ref: https://github.com/redis/redis-py/pull/3622
=> fix JSON stats view and tests with redis-py 6.0

django_rq/templates/django_rq/scheduler.html
This PR updates `scheduler.html` to correctly display the job status by using `job.get_status.value` instead of `job.get_status`.  
- Updated job status display in `scheduler.html`.  
- Affects the scheduler view at `/django-rq/schedulers/<scheduler_id>/`.  
- Verified that the job status is displayed correctly in the scheduler view.  
- Ensured no other UI elements were affected.
=> [FIX] -- job status display in scheduler listing page template.

django_rq/__init__.py
based on [pyright doc](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface), imported symbols are considered private by default. 
without this change, pyright will report error: `"get_queue" is not exported from module "django_rq" (reportPrivateImportUsage)`
=> fix pyright check

README.rst, django_rq/decorators.py, django_rq/queues.py, django_rq/tests/tests.py
The PR is fixing issue #705.
Since there are 3 places where the result_ttl can be set, the PR aims to set the order as:
- the decorator `result_ttl`
- the `settiings.RQ_QUEUES[queue_name]['DEFAULT_RESULT_TTL']`.
- the `settings.RQ` DEFAULT_RESULT_TTL, and
=> fix job decorator default ttl

README.rst, django_rq/stats_views.py, django_rq/templates/django_rq/stats.html, django_rq/tests/test_views.py, django_rq/urls.py
This PR adds token capability to the /metrics/ endpoint, just like how it's done on the /stats.json/ endpoint.
If you need to access the metrics view via other HTTP clients (for monitoring purposes), you can define RQ_API_TOKEN and access it via /django-rq/metrics/<API_TOKEN>.
-----
**Update:**
This PR replaces the token URL and replaces it with header authorization by using the bearer format.
Additionally, it adds the same token auth capability to the new prometheus /metrics/ endpoint and adds a link to the metrics page alongside the json link in the admin panel.
=> Change url token to header auth and add to /metrics/ aswell
