django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html
=> Remove redundant get_status checks.

README.rst
We added some templates to make the admin look nice with [django-suit](http://djangosuit.com/). I'm not sure if this is something you'd be interesting in including or not, so I added README. If you do want to include it, but have a better place, let me know and I can move it.
=> Add message about django-suit integration

django_rq/management/commands/rqworker.py, django_rq/workers.py
=> Allow exception handlers to be defined in settings

django_rq/management/commands/rqworker.py
This is practically a copy-paste from RQ's cli (:
=> Added pid option that mimics the same option on RQ's cli

django_rq/templates/django_rq/clear_queue.html, django_rq/templates/django_rq/confirm_action.html, django_rq/templates/django_rq/delete_job.html, django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html, django_rq/templatetags/jquery_path.py, django_rq/views.py
=> Django 1.9 compatibility

django_rq/management/commands/rqscheduler.py
=> Add '-i' option in rqscheduler

.travis.yml
Updated travis matrix to run tests only for officialy supported django versions.
=> Updated travis matrix

django_rq/management/commands/rqenqueue.py, django_rq/management/commands/rqscheduler.py, django_rq/management/commands/rqworker.py
=> replaced options with ArgumentParser

django_rq/management/commands/rqworker.py
This fixes #180 on Django 1.10
=> Queues are not passed via command line

django_rq/management/commands/rqenqueue.py, django_rq/management/commands/rqscheduler.py
hello there are two little changes
1. fixed the rqenqueue command on --timeout option
2. added a --pid option to the rqscheduler command (adapted from the one in rqworker)
best regards
=> rqenqueue fix and rqscheduler enhancement

django_rq/views.py
=> Fix view paging for registry-based job lists

django_rq/templates/django_rq/jobs.html
With it you can  add in your project template forder a new directory called
django_rq/<html_name>.html
Ex.:
templates/jobs.html
```
{% extends "django_rq/jobs.html" %}
{% block extra_columns %}
{{ block.super }}
{% if queue.name == 'failed' %}
<th><div class = 'text'><span>Origin</span></div></th>
<th><div class = 'text'><span>Args</span></div></th>
<th><div class = 'text'><span>Kwags</span></div></th>
{% endif %}
{% endblock extra_columns %}
{% block extra_columns_values %}
{{ block.super }}
<td>{{ job.origin }}</td>
<td>{{ job.args }}</td>
<td>{{ job.kwargs }}</td>
{% endblock extra_columns_values %}
```
=> Adds possibility to add custom columns

django_rq/templates/django_rq/worker_details.html, django_rq/utils.py, django_rq/views.py
* Fix #264 
* Fix #261 
* Fix other small minor statistics bug
=> Fix statistics bug

django_rq/urls.py
* Add fix for supporting Django `2.0` and greater
* Add fallback for Django `1.11` and older
=> Fixed supporting for Django 2.0 and greater

README.rst
I hope this is helpful to those who come next... Could us some additional refinement I'm sure.
=> How to run the RQ Worker as a service

.travis.yml
=> Add Django 2.06 to Travis.yml

.travis.yml
=> Update to latest Django Version

django_rq/templates/django_rq/job_detail.html, django_rq/tests/test_views.py, django_rq/urls.py, django_rq/views.py, setup.py
I added a view to enable user to force enqueue deferred job
=> Enqueue job view

django_rq/management/commands/rqscheduler.py, django_rq/management/commands/rqworker.py, django_rq/tests/tests.py
Both `rq` and `rq_shceduler` have their own version of `setup_loghandlers` function in their code. This PR updates both `rqworker` and `rqscheduler` commands to call those functions.
This closes #91, closes #191.
=> Logging configuration for worker and scheduler

.gitignore, .travis.yml, django_rq/__init__.py, django_rq/management/commands/rqworker.py, django_rq/queues.py, django_rq/settings.py, django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html, django_rq/templates/django_rq/stats.html, django_rq/templates/django_rq/workers.html, django_rq/tests/settings.py, django_rq/tests/test_views.py, django_rq/tests/tests.py, django_rq/tests/utils.py, django_rq/urls.py, django_rq/utils.py, django_rq/views.py, setup.py
=> Support for RQ v1.0

django_rq/tests/test_views.py, django_rq/views.py
Address #390 
Gracefully continue if a job being requeued no longer exists. Update messaging to be a little more precise. :small_airplane:
=> Gracefully hand NoSuchJobError when requeuing all jobs

django_rq/templates/django_rq/job_detail.html
This can be useful for debugging/maintenance, why not to include meta field?
=> Admin improvement: add job.meta to job_detail.html

django_rq/views.py
According to #492 added "@never_cache" to all django-rq views
=> Added never_cache to all views

django_rq/queues.py
=> Allow SSL_CERT_REQS to work alongside URL configs

django_rq/views.py
Similar to the issue reported in #504 we had some sync issues. Here is the PR of the solution @selwin suggested.
Please do let me know if I can improve in any way.
Also would be nice to get a new release, with all the changes, merged since 2.4.1. @selwin do let me know please if I can be any help.
=> Sync worker count before displaying on Dashboard

django_rq/templates/django_rq/stats.html
=> Change h1 text in stats template

django_rq/templates/django_rq/job_detail.html, django_rq/templates/django_rq/jobs.html, django_rq/tests/test_views.py, django_rq/urls.py, django_rq/utils.py, django_rq/views.py
Adds #573, action to stop a job. Current behavior deletes the entry but does not stop the job. 
@selwin
=> Add Stop Jobs action

django_rq/templates/django_rq/jobs.html
Fixes https://github.com/rq/django-rq/issues/603
=> Only show "Empty Queue" button when displaying queued jobs

django_rq/templates/django_rq/jobs.html, django_rq/templates/django_rq/stats.html
This PR updates templates to better match with those of Django 4.2
=> Update templates to match with current Django Admin

django_rq/queues.py, django_rq/tests/tests.py
=> get_scheduler: allow passing a custom connection object
